version: "3"
services:
  nginx:
    image: steveltn/https-portal:1.20.1
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      # Nginxの設定ファイルを上書きする
      - ./build/nginx/baetoru.ssl.conf.erb:/var/lib/nginx-conf/localhost.ssl.conf.erb:ro
      - https-portal-data:/var/lib/https-portal
    environment:
      STAGE: local
      DOMAINS: "localhost"
    depends_on:
      - app
      - front
    networks:
      - baetoru-network

  db:
    image: mysql:8.0
    command: mysqld
    volumes:
      # MySQLの設定ファイル
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # DBのデータを永続化する
      - db-data:/var/lib/mysql
    # environmentはenv_fileの前に読み込まれるのでenv_fileで直接環境変数を設定する
    env_file:
      - .env
    networks:
      - baetoru-network
    ports:
      - 3306:3306

  migration:
    image: flyway/flyway
    volumes:
      - ./database/migration/schema:/flyway/sql
    depends_on:
      - db
    networks:
      - baetoru-network

  app:
    build:
      context: ./server/
      dockerfile: docker/dev/Dockerfile
    command: reflex -r '\.go$$' -s -- sh -c 'go build -o /baetoru . && /baetoru'
    volumes:
    - ./server:/workdir
    depends_on:
      - db
    env_file:
      - .env
      - .env.secret
    networks:
      - baetoru-network

  front:
    build:
      context: ./frontend/
      dockerfile: docker/dev/Dockerfile
    command: npm run dev
    volumes:
      - ./frontend/:/workdir
      - ignore:/workdir/node_modules
    working_dir: /workdir
    env_file:
      - .env
      - .env.secret
    networks:
      - baetoru-network

volumes:
  db-data:
  ignore:
  https-portal-data:

networks:
  baetoru-network:
    driver: bridge
