version: '3'
services:
  nginx:
    image: nginx:1.19.9-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginxの設定ファイルを上書きする
      - ./build/nginx/mesimasi.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./docker/nginx/conf/key.pem:/etc/ssl/private/key.pem:ro
#      - ./docker/nginx/conf/cert.pem:/etc/ssl/certs/cert.pem:ro
#      - ./docker/nginx/conf/dhparam.pem:/etc/nginx/ssl/dhparam.pem
    networks:
      - baetoru-network

  db:
    image: mysql:8.0
    command: mysqld
    volumes:
      # MySQLの設定ファイル
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # DBのデータを永続化する
      - db-data:/var/lib/mysql
    # environmentはenv_fileの前に読み込まれるのでenv_fileで直接環境変数を設定する
    env_file:
      - .env
    networks:
      - baetoru-network

  app:
    build:
      context: ./server/
      dockerfile: server/docker/Dockerfile
    command: /baetoru
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - baetoru-network

  front:
      build:
        context: ./frontend/
        dockerfile: docker/prod/Dockerfile
      command: npm run start
      environment:
        - .env
      networks:
        - blog-network

volumes:
  db-data:

networks:
  baetoru-network:
    driver: bridge