import type { NextPage } from 'next';
// import { Box, Text } from '@chakra-ui/react';
// import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      hello world
    </>
    // <Box>
    //   <Text>Hello world</Text>
    //   {/* <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head> */}
    // </Box>
  )
}

export default Home
