name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          workdir: ./frontend/
          reporter: github-pr-review
          eslint_flags: './**/*.{js,jsx,ts,tsx}'

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: server/
          golangci_lint_flags: '--out-format=github-actions --enable=golint,gosec,prealloc,gocognit,bodyclose,gofmt'